name: Build/release
on:
  push:
    branches:
      - main
    tags:
      # Build on every tag in the form v1.2.3-something.4
      - "v*"
defaults:
  run:
    shell: bash # Run everything using bash

jobs:
  build_macos:
    name: macOS build
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./scripts/get-pkg-version.js)
          echo ::set-output name=version::$pkgver
      # Save the macOS certificate on this runner for forge to access it in the
      # next step below.
      - name: Retrieve code signing certificate
        run: |
          sh ./scripts/add-osx-cert.sh
        env:
          MAC_CERTS: ${{ secrets.MAC_CERTS }}
          MAC_CERTS_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
      - name: Set up build environment
        run: |
          yarn install
      - name: Angular build
        run: |
          yarn run build:prod
      - name: MacOS Build
        run: |
          npx electron-builder build --mac
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
      - name: MacOS zip file
        uses: actions/upload-artifact@v1
        with:
          name: MagicBox-${{steps.ref.outputs.version}}.dmg
          path: ./release/MagicBox-${{steps.ref.outputs.version}}.dmg
      - name: MacOS ZIP release
        uses: actions/upload-artifact@v1
        with:
          name: MagicBox-${{steps.ref.outputs.version}}-mac.zip
          path: ./release/MagicBox-${{steps.ref.outputs.version}}-mac.zip
      - name: Checksums file
        uses: actions/upload-artifact@v1
        with:
          name: latest-mac.yml
          path: ./release/latest-mac.yml
  #
  #
  #
  prepare_release:
    name: Prepare release draft
    # Make sure (and wait until) the builds have succeeded
    needs: [build_macos]
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Retrieve tag version
        id: ref
        run: |
          pkgver=$(node ./scripts/get-pkg-version.js)
          echo ::set-output name=version::$pkgver
      # First, download all resulting assets from the previous steps.
      - name: Download macOS image
        uses: actions/download-artifact@v1
        with:
          name: MagicBox-${{steps.ref.outputs.version}}.dmg
          path: .
      - name: Download macOS zip file
        uses: actions/download-artifact@v1
        with:
          name: MagicBox-${{steps.ref.outputs.version}}-mac.zip
          path: .
      - name: Download the checksums file
        uses: actions/download-artifact@v1
        with:
          name: latest-mac.yml
          path: .
      - name: Create a new release draft
        id: create_release
        uses: actions/create-release@v1
        with:
          github_token: ${{ secrets.github_token }}
          tag_name: ${{steps.ref.outputs.version}} # tag_name is required, but can be overridden during edit
          release_name: Release ${{steps.ref.outputs.version}} # release_name is required
          body: If you can read this, I have forgotten to fill in the changelog. Sorry!
          draft: true # Always create as draft, so that we can populate the remaining values easily

      # And finally, upload app files
      - name: Upload macOS image
        uses: actions/upload-release-asset@v1.0.1
        with:
          github_token: ${{ secrets.github_token }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MagicBox-${{steps.ref.outputs.version}}.dmg
          asset_name: MagicBox-${{steps.ref.outputs.version}}.dmg
          asset_content_type: application/octet-stream
      - name: Upload macOS zip file
        uses: actions/upload-release-asset@v1.0.1
        with:
          github_token: ${{ secrets.github_token }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MagicBox-${{steps.ref.outputs.version}}-mac.zip
          asset_name: MagicBox-${{steps.ref.outputs.version}}-mac.zip
          asset_content_type: application/zip
      - name: Upload the checksums
        uses: actions/upload-release-asset@v1.0.1
        with:
          github_token: ${{ secrets.github_token }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./latest-mac.yml
          asset_name: latest-mac.yml
          asset_content_type: application/x-yaml
